from enum import Enum


class EnterpriseEventType(str, Enum):

    MATHEMATICAL_STATE = "MATHEMATICAL_STATE"
    GRAPH_UPDATED = "GRAPH_UPDATED"
    EVOLUTION_COMPLETED = "EVOLUTION_COMPLETED"

    COGNITIVE_REQUEST = "COGNITIVE_REQUEST"
    COGNITIVE_RESPONSE = "COGNITIVE_RESPONSE"

    TENSOR_UPDATE = "TENSOR_UPDATE"
    TENSOR_FUSED = "TENSOR_FUSED"

    VALIDATION_COMPLETED = "VALIDATION_COMPLETED"

    RUNTIME_ALERT = "RUNTIME_ALERT"

    LEARNING_SIGNAL = "LEARNING_SIGNAL"

    DECISION_REQUEST = "DECISION_REQUEST"
    DECISION_COMPLETED = "DECISION_COMPLETED"

    ERROR = "ERROR"